### ISSUE TITLE
Dont get any response back.

### ISSUE THREAD

**Issue by pantonis** [sjmf/ng2-stompjs-demo#20]
I run the example, connecting succesfully, sending the message (can see it in RMQ web ui but I dont get the message back. No errors in console

**Comment by JimiC** [comment]
Check that you have subscribed to the queue (config).

**Comment by pantonis** [comment]
I have subscribed to the queue.

```
{
    "host": "127.0.0.1",
    "port": 15674,
    "https": false,

    "user": "test",
    "pass": "test",

    "subscribe": ["/topic/ng-demo-sub"],
    "publish": ["/topic/ng-demo-pub"],

    "heartbeat_in": 0,
    "heartbeat_out": 20000,

    "debug": true
}
```

**Comment by JimiC** [comment]
Have you configured RMQ to push the message from the `pub` to the `sub` queue?

**Comment by pantonis** [comment]
Configure it to push from pub to sub? Can you explain please?

When I use the Web UI to publish a message to the ng-demo-sub routing key I get it on the ng2 app

**Comment by sjmf** [comment]
Yep, try:
```
    "subscribe": ["/topic/ng-demo"],
    "publish": ["/topic/ng-demo"],
```

so they're both the same.

**Comment by pantonis** [comment]
oh didn't see the suffixes in the config.

:)

Thanks

**Comment by JimiC** [comment]
As @sjmf said if you set `subscribe` and `publish` to point to the same queue then you will get the message back, but usually in real apps the `pub` and `sub` queues are not the same queues. To simulate that something read the `pub` and answered to the `sub` you usually `bind` the queues in RMQ. Check out the RMQ manual.

**Comment by pantonis** [comment]
Yes it was a typo
